name: walletconnect_dart
description: Open protocol for connecting decentralised applications to mobile wallets with QR code scanning or deep linking.
version: 0.0.11
homepage: https://walletconnect.org/
repository: https://github.com/RootSoft/walletconnect-dart-sdk
issue_tracker: https://github.com/RootSoft/walletconnect-dart-sdk/issues

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:

  flutter:
    sdk: flutter
  # WebSocket Channel
  web_socket_channel: ^2.4.0

  # UUID
  uuid: ^3.0.7

  # Cryptography
  cryptography: ^2.5.0

  # Hex
  convert: ^3.1.1

  # JSON Annotation
  json_annotation: ^4.8.1

  # Stack trace
  stack_trace: ^1.11.0

dev_dependencies:
  # Testing framework
  test: ^1.24.3

  # JSON Serialization
  json_serializable: ^6.7.0

  # Build runner
  build_runner: ^2.4.4